name: DynmapAutoMarker
main: be.frostyfeet.minecraft.dynmap.AutoMarkerPlugin
version: 2.1.0
api-version: 1.19
depend: [dynmap]
commands:
  ffmap:
    description: Shortcuts for adding markers on your Dynmap
    usage: /ffmap < town | portal | ship | temple | tower | mineshaft > "Name"
